//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKartDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public long PurchaseId { get; set; }
        public string EmailId { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public short QuantityPurchased { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
