//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKartDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<byte> CategoryId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public System.DateTime PurchaseDate { get; set; }
    }
}
